spring:
  profiles:
    group:
      dev: common, local
      test: common, test
      prod: prod
---
# H2 common 환경
spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;NON_KEYWORDS=USER,ORDER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    com:
      flab:
        auctionhub:
          repository:
            mybatis: trace
    root: debug

mybatis:
  type-aliases-package: com.flab.auctionhub.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.flab.auctionhub.hadler

---
# H2 local 환경
spring:
  config:
    activate:
      on-profile: local

  sql:
    init:
      schema-locations: classpath*:schema.sql
      data-locations: classpath*:data.sql
      mode: always

---
# H2 test 환경
spring:
  config:
    activate:
      on-profile: test

  sql:
    init:
      schema-locations: classpath*:schema.sql
      data-locations: classpath*:data-test.sql
      mode: always

---
# MySQL dev 환경
spring:
  config:
    activate:
      on-profile: prod
